//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public int SсheduleId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> DayOfWeekId { get; set; }
        public Nullable<int> TimeId { get; set; }
        public Nullable<int> TypeOfWeekId { get; set; }
        public Nullable<int> AuditoriaId { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public Nullable<int> LecturerId { get; set; }
    
        public virtual Auditorias Auditorias { get; set; }
        public virtual DaysOfWeek DaysOfWeek { get; set; }
        public virtual Disciplines Disciplines { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Lecturers Lecturers { get; set; }
        public virtual Times Times { get; set; }
        public virtual TypesOfWeek TypesOfWeek { get; set; }
    }
}
